name: "headstudio"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "./outputs"
seed: 0

#data_type: "random-camera-w-cond-datamodule"
data_type: "random-camera-exp-datamodule"
data:
  batch_size: 8
  eval_camera_distance: 2.0
  camera_distance_range: [ 1.5, 2.0 ]
  light_sample_strategy: "dreamfusion3dgs"
  height: 1024
  width: 1024
  eval_height: 1024
  eval_width: 1024
  elevation_range: [ -30, 30 ]
  is_lmk: True
  is_mediapipe: True

  enable_near_head_poses: true
  head_offset: 0.65
  head_camera_distance_range: [ 0.4, 0.6 ]
  head_prob: 0.25
  head_start_step: 1200
  head_end_step: 3600
  head_azimuth_range: [ 0, 180 ]

  enable_near_back_poses: true
  back_offset: 0.65
  back_camera_distance_range: [ 0.6, 0.8 ]
  back_prob: 0.20
  back_start_step: 1200
  back_end_step: 3600
  back_azimuth_range: [ -180, 0 ]

  gender: 'generic'
  training_w_animation: True
  flame_path: "./ckpts/FLAME-2000"
  talkshow_train_path: './talkshow/collection/chemistry_exp.npy'
  talkshow_val_path: './talkshow/ExpressiveWholeBodyDatasetReleaseV1.0/chemistry/2nd_Order_Rate_Laws-6BZb96mqmbg.mp4/68891-00_01_40-00_01_46/68891-00_01_40-00_01_46.pkl'

system_type: "head-3dgs-lks-rig-system"
system:
  radius: ${data.eval_camera_distance}
  texture_structure_joint: true
  flame_path: ${data.flame_path}
  disable_hand_densification: false
  pts_num: 100000
  densify_prune_start_step: 300 # 300
  densify_prune_end_step: 2100 # 2100
  densify_prune_interval: 300 # 300
  shape_update_end_step: 7000
  size_threshold: 60
  max_grad: 0.002 # 0.0002
  flame_gender: ${data.gender}
  prune_only_start_step: 2400 # 2400
  prune_only_end_step: 3300 # 3300
  prune_only_interval: 300 # 300
  prune_size_threshold: 0.002
  half_scheduler_max_step: 3000
  size_threshold_fix_step: 1500
  apose: true
  bg_white: False
  area_relax: False
  training_w_animation: ${data.training_w_animation}

  guidance_type: "controlnet-depth-guidance"
  guidance:
    pretrained_model_name_or_path: "stablediffusionapi/realistic-vision-51"
    control_type: "mediapipe" # depth
    min_step_percent: 0.05
    max_step_percent: 0.8
    use_nfsd: False
    use_dsd: False

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stablediffusionapi/realistic-vision-51"
    prompt: "Elon Musk, RAW photo, (high detailed skin:1.2), 8k uhd, dslr, soft lighting, high quality, film grain, Fujifilm XT3"
    negative_prompt: "shadow, dark face, eyeglass, glasses, noise,pattern, strange color, (deformed iris, deformed pupils, semi-realistic, cgi, 3d, render, sketch, cartoon, drawing, anime:1.4), text, close up, cropped, out of frame, worst quality, low quality, jpeg artifacts, ugly, duplicate, morbid, mutilated, poorly drawn face, mutation, deformed, blurry, dehydrated, bad anatomy, bad proportions, extra limbs, cloned face, disfigured, gross proportions,long neck"

  loggers:
    wandb:
      enable: false
      project: 'threestudio'
      name: None

  loss:
    lambda_sds: 1.
    lambda_sparsity: 1.
    lambda_opaque: 0.0
    lambda_position: 10.0
    lambda_scaling: 10.0
    lambda_shape: 0.0
  optimizer:
    name: Adam
    args:
      lr: 0.001
      betas: [ 0.9, 0.99 ]
      eps: 1.e-15

trainer:
  max_steps: 10000
  log_every_n_steps: 1
  num_sanity_val_steps: 0
  val_check_interval: 100
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
